[package]
name = "kallipctl"
description = "Management CLI (kallipctl) for the kallipai local daemon"
edition = "2024"
version.workspace = true
license.workspace = true

[dependencies]
kallipai-daemon-client = { workspace = true }
kallipai-blob-store = { workspace = true }
kallipai-daemon-common = { workspace = true }
kallipai-common = { workspace = true }
dirs = { workspace = true }
libc = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true, features = ["unstable-dynamic"] }
tokio = { workspace = true, features = [
  "io-util",
  "net",
  "rt",
  "macros",
  "time",
  "signal",
] }

[dev-dependencies]
tempfile = { workspace = true }
