//! Agent identifier type.
//!
//! Generated by [`crate::id_type!`]; see that macro for the full impl surface.

crate::id_type! {
    /// Unique identifier for an agent instance.
    ///
    /// Thin wrapper around a UUID string - provides type safety without format
    /// validation. Use [`AgentId::random()`] to generate a new one.
    AgentId
}
